import { describe, it, expect } from 'vitest';
import parseStatBlockText from '../src/utils/statBlockParser';
import { generateQuickNPC, exportNPCToMarkdown } from '../src/utils/npcUtils';
import exporter from '../src/utils/exporters/htmlExporter';

describe('StatBlock Parser', () => {
  it('parses detailed NPC markdown generated by exportNPCToMarkdown', () => {
    const npc = generateQuickNPC();
    const md = exportNPCToMarkdown(npc);
    const res = parseStatBlockText(md);
    expect(res.type).toBe('detailed');
    expect(res.data?.name).toBe(npc.name);
    // activeDefense was defined
    expect(res.diagnostics.issues.length).toBeLessThan(2);
  });

  it('parses simple quick stat block text', () => {
    const qsb = `# Dire Wolf
Active Defense: 15
Passive Defense: 5
Spirit Points: 3
Battle Phase: d6
Prowess Die: d8
HP: 10 (5/5)`;
    const res = parseStatBlockText(qsb);
    expect(res.type).toBe('quick');
    expect(res.data?.name?.toLowerCase()).toContain('dire wolf');
    expect(parseInt((res.data as any).activeDefense)).toBe(15);
    expect(parseInt((res.data as any).passiveDefense)).toBe(5);
  });
});

describe('HTML Exporter', () => {
  it('creates HTML from NPC object and wraps for Word', () => {
    const npc = generateQuickNPC();
    const html = exporter.npcToHTML(npc as any);
    expect(html).toContain(npc.name);
    const wrapped = exporter.wrapForWord(html);
    expect(wrapped.startsWith('<!doctype html>')).toBe(true);
  });
});
